/*!
* \file   HypoplasticClayModelWrapper.cxx
* \brief  this file implements the HypoplasticClayModelWrapper Behaviour.
*         File generated by tfel version 4.1.0-dev
* \author Thomas Helfer
* \date   11 / 02 / 2021
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/HypoplasticClayModelWrapperBehaviourData.hxx"
#include"TFEL/Material/HypoplasticClayModelWrapperIntegrationData.hxx"
#include"TFEL/Material/HypoplasticClayModelWrapper.hxx"

namespace tfel::material{

HypoplasticClayModelWrapperTridimensionalParametersInitializer&
HypoplasticClayModelWrapperTridimensionalParametersInitializer::get()
{
static HypoplasticClayModelWrapperTridimensionalParametersInitializer i;
return i;
}

HypoplasticClayModelWrapperTridimensionalParametersInitializer::HypoplasticClayModelWrapperTridimensionalParametersInitializer()
{
// Reading parameters from a file
HypoplasticClayModelWrapperTridimensionalParametersInitializer::readParameters(*this,"HypoplasticClayModelWrapper-parameters.txt");
HypoplasticClayModelWrapperTridimensionalParametersInitializer::readParameters(*this,"HypoplasticClayModelWrapperTridimensional-parameters.txt");
}

void
HypoplasticClayModelWrapperTridimensionalParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("minimal_time_step_scaling_factor",key)==0){
HypoplasticClayModelWrapperParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
HypoplasticClayModelWrapperParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else {
tfel::raise("HypoplasticClayModelWrapperTridimensionalParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
HypoplasticClayModelWrapperTridimensionalParametersInitializer::readParameters(HypoplasticClayModelWrapperTridimensionalParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
auto line = std::string{};
while(std::getline(f,line)){
auto tokens = tokenize(line);
auto throw_if = [ln = ln, line, fn](const bool mfront_c,
const std::string& mfront_error_message){
tfel::raise_if(mfront_c,"HypoplasticClayModelWrapperTridimensionalParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+mfront_error_message+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("minimal_time_step_scaling_factor"==tokens[0]){
HypoplasticClayModelWrapperParametersInitializer::get().set("minimal_time_step_scaling_factor",
HypoplasticClayModelWrapperParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
HypoplasticClayModelWrapperParametersInitializer::get().set("maximal_time_step_scaling_factor",
HypoplasticClayModelWrapperParametersInitializer::getDouble(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

HypoplasticClayModelWrapperParametersInitializer&
HypoplasticClayModelWrapperParametersInitializer::get()
{
static HypoplasticClayModelWrapperParametersInitializer i;
return i;
}

HypoplasticClayModelWrapperParametersInitializer::HypoplasticClayModelWrapperParametersInitializer()
{
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
// Reading parameters from a file
HypoplasticClayModelWrapperParametersInitializer::readParameters(*this,"HypoplasticClayModelWrapper-parameters.txt");
}

void
HypoplasticClayModelWrapperParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else {
tfel::raise("HypoplasticClayModelWrapperParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

double
HypoplasticClayModelWrapperParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"HypoplasticClayModelWrapperParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

void
HypoplasticClayModelWrapperParametersInitializer::readParameters(HypoplasticClayModelWrapperParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
auto line = std::string{};
while(std::getline(f,line)){
auto tokens = tokenize(line);
auto throw_if = [ln = ln, line, fn](const bool mfront_c,
const std::string& mfront_error_message){
tfel::raise_if(mfront_c,"HypoplasticClayModelWrapperParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+mfront_error_message+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = HypoplasticClayModelWrapperParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = HypoplasticClayModelWrapperParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

