if(ZSET_INSTALL_PATH)
  set(ZSETHOME "${ZSET_INSTALL_PATH}")
else(ZSET_INSTALL_PATH)
  set(ZSETHOME $ENV{ZSETHOME})
endif(ZSET_INSTALL_PATH)

if(ZSETHOME)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(ZSET_CPPFLAGS "-DLinux")
  else(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "The zmat interface is only supported under linux")
  endif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  find_path(ZSET_INCLUDE_DIR Behavior.h
    HINTS ${ZSETHOME}/include)
  if(ZSET_INCLUDE_DIR STREQUAL "ZSET_INCLUDE_DIR-NOTFOUND")
    message(FATAL_ERROR "Behavior.h not found")
  endif(ZSET_INCLUDE_DIR STREQUAL "ZSET_INCLUDE_DIR-NOTFOUND")
  message(STATUS "ZSET include files path detected: [${ZSET_INCLUDE_DIR}].")
else(ZSETHOME)
  message(FATAL_ERROR "no ZSETHOME defined")
endif(ZSETHOME)

